<?php

/**
 * PluginaPageToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPageToASearchDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPageToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPageToASearchDocument');
    }
}