<?php

/**
 * PluginaSearchUsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaSearchUsageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaSearchUsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaSearchUsage');
    }
}