<?php

/**
 * PluginaMediaItemToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaMediaItemToASearchDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaMediaItemToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaMediaItemToASearchDocument');
    }
}