<?php

/**
 * aPaypalButtonSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPaypalButtonSlotTable extends PluginaPaypalButtonSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPaypalButtonSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPaypalButtonSlot');
    }
}