<?php

/**
 * aWufooFormSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aWufooFormSlotTable extends PluginaWufooFormSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aWufooFormSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aWufooFormSlot');
    }
}