<?php

/**
 * aMediaItemToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aMediaItemToASearchDocumentTable extends PluginaMediaItemToASearchDocumentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aMediaItemToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aMediaItemToASearchDocument');
    }
}