<?php

/**
 * aPageToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPageToASearchDocumentTable extends PluginaPageToASearchDocumentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPageToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPageToASearchDocument');
    }
}