<?php

/**
 * aSearchUsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aSearchUsageTable extends PluginaSearchUsageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aSearchUsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aSearchUsage');
    }
}