<?php

/**
 * BaseaSearchDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $culture
 * @property clob $info
 * @property Doctrine_Collection $aPage
 * @property Doctrine_Collection $aMediaItem
 * @property Doctrine_Collection $Usages
 * @property Doctrine_Collection $aPageToASearchDocument
 * @property Doctrine_Collection $aMediaItemToASearchDocument
 * 
 * @method varchar             getCulture()                     Returns the current record's "culture" value
 * @method clob                getInfo()                        Returns the current record's "info" value
 * @method Doctrine_Collection getAPage()                       Returns the current record's "aPage" collection
 * @method Doctrine_Collection getAMediaItem()                  Returns the current record's "aMediaItem" collection
 * @method Doctrine_Collection getUsages()                      Returns the current record's "Usages" collection
 * @method Doctrine_Collection getAPageToASearchDocument()      Returns the current record's "aPageToASearchDocument" collection
 * @method Doctrine_Collection getAMediaItemToASearchDocument() Returns the current record's "aMediaItemToASearchDocument" collection
 * @method aSearchDocument     setCulture()                     Sets the current record's "culture" value
 * @method aSearchDocument     setInfo()                        Sets the current record's "info" value
 * @method aSearchDocument     setAPage()                       Sets the current record's "aPage" collection
 * @method aSearchDocument     setAMediaItem()                  Sets the current record's "aMediaItem" collection
 * @method aSearchDocument     setUsages()                      Sets the current record's "Usages" collection
 * @method aSearchDocument     setAPageToASearchDocument()      Sets the current record's "aPageToASearchDocument" collection
 * @method aSearchDocument     setAMediaItemToASearchDocument() Sets the current record's "aMediaItemToASearchDocument" collection
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaSearchDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_search_document');
        $this->hasColumn('culture', 'varchar', 5, array(
             'type' => 'varchar',
             'length' => 5,
             ));
        $this->hasColumn('info', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('aPage', array(
             'refClass' => 'aPageToASearchDocument',
             'local' => 'a_search_document_id',
             'foreign' => 'a_page_id'));

        $this->hasMany('aMediaItem', array(
             'refClass' => 'aMediaItemToASearchDocument',
             'local' => 'a_search_document_id',
             'foreign' => 'a_media_item_id'));

        $this->hasMany('aSearchUsage as Usages', array(
             'local' => 'id',
             'foreign' => 'document_id'));

        $this->hasMany('aPageToASearchDocument', array(
             'local' => 'id',
             'foreign' => 'a_search_document_id'));

        $this->hasMany('aMediaItemToASearchDocument', array(
             'local' => 'id',
             'foreign' => 'a_search_document_id'));
    }
}