<?php

/**
 * aSearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aSearchDocumentTable extends PluginaSearchDocumentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aSearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aSearchDocument');
    }
}