<?php

/**
 * BaseaCacheItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $k
 * @property blob $value
 * @property integer $timeout
 * @property integer $last_mod
 * 
 * @method varchar    getK()        Returns the current record's "k" value
 * @method blob       getValue()    Returns the current record's "value" value
 * @method integer    getTimeout()  Returns the current record's "timeout" value
 * @method integer    getLastMod()  Returns the current record's "last_mod" value
 * @method aCacheItem setK()        Sets the current record's "k" value
 * @method aCacheItem setValue()    Sets the current record's "value" value
 * @method aCacheItem setTimeout()  Sets the current record's "timeout" value
 * @method aCacheItem setLastMod()  Sets the current record's "last_mod" value
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaCacheItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_cache_item');
        $this->hasColumn('k', 'varchar', 255, array(
             'type' => 'varchar',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('timeout', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_mod', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}