<?php

/**
 * aEmbedFormSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEmbedFormSlotTable extends PluginaEmbedFormSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEmbedFormSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEmbedFormSlot');
    }
}