<?php

/**
 * PluginaSearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaSearchDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaSearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaSearchDocument');
    }
}