<?php

/**
 * PluginaSearchWordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaSearchWordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaSearchWordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaSearchWord');
    }
}